image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
     # runs during prebuild
  - init: |
      export NG_CLI_ANALYTICS="ci" 
      npm install
      npm run build:app
      gp sync-done install
    # runs on startup
    command: npm run start
  - init: gp sync-await install
    command: npm run test --watch
    openMode: split-right
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false