# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm install codecov -g
      npm run build:lib
      npm run test -- --code-coverage
      npm run e2e
      codecov
    displayName: 'npm install, build and test'
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage Angular results - App'
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverage/cobertura-coverage.xml'
      reportDirectory: coverage
      failIfCoverageEmpty: true

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage Angular results - Package'
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'projects/coverage/cobertura-coverage.xml'
      reportDirectory: projects/coverage
      failIfCoverageEmpty: true

  - task: PublishTestResults@1
    displayName: 'Publish Angular test results - App'
    condition: succeededOrFailed()
    inputs:
      searchFolder: $(System.DefaultWorkingDirectory)junit
      testRunTitle: Angular
      testResultsFormat: JUnit
      testResultsFiles: '**/TESTS*.xml'

  - task: PublishTestResults@2
    displayName: 'Publish Angular test results - Package'
    condition: succeededOrFailed()
    inputs:
      searchFolder: $(System.DefaultWorkingDirectory)projects/junit
      testRunTitle: Angular
      testResultsFormat: JUnit
      testResultsFiles: '**/TESTS*.xml'

  - task: PublishTestResultsE2e
    displayName: 'Publish Angular E2E test results'
    condition: succeededOrFailed()
    inputs:
      searchFolder: $(System.DefaultWorkingDirectory)e2e/junit
      testRunTitle: Angular_E2E
      testResultsFormat: JUnit
      testResultsFiles: '**/junit*.xml'

  - script: |
      npm run semantic-release
    displayName: 'release'
    env:
      GH_TOKEN: $(GITHUB_PAT)
      NPM_TOKEN: $(NPM_PAT)
      NPM_USERNAME: $(NPM_USER)
