name: Build
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 14.x
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
          cache: npm
    
      - run: 'npm install'
    
      - run: 'npm run build:lib'
    
      - run: 'npm run test -- --code-coverage'
        name: 'unit test'  
    
      - run: 'npm run e2e'
    
      - name: 'publish coverage'
        run: |
          npm install codecov -g
          codecov
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)
    
      - name: 'release'
        if: github.ref == 'refs/heads/master'
        run: |
          npm run semantic-release
        env:
          GH_TOKEN: $(GITHUB_PAT)
          NPM_TOKEN: $(NPM_PAT)
          NPM_USERNAME: $(NPM_USER)                
